{% set name = "contact_map" %}
{% set version = "0.5.1" %}
{% set sha256 = "fa7bb768a8d7348d449e30709c8e07da54b247fc8db913b9c753112f5cc4bca6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - future
    - numpy
    - mdtraj
    - pandas

test:
  imports:
    - contact_map

about:
  home: http://github.com/dwhswenson/contact_map
  license: LGPL-2.1+
  license_family: LGPL
  license_file: LICENSE
  summary: Contact maps based on MDTraj
  description: |
    Contact maps based on MDTraj; useful for studying for intramolecular
    and intermolecular contacts from simulations of biomolecular systems.
    For a more detailed description, see package's documentation.
  dev_url: https://github.com/dwhswenson/contact_map

extra:
  recipe-maintainers:
    - dwhswenson
    - sroet
