travis:
  secure:
    BINSTAR_TOKEN: W4QN3U6sb9/jIvmTeRnvNzuNwdgzA8Pqva3D1Uam2Euakdw5xqXdSuMXMb6RAUZFpF62ySjc4cRF9wfBRCFwFUr6phM/afe/s5b3rGSf0ngilJdtCf1W/US02+oSnCrnKviP+oyELlg5w3219/sn0qbWF4Rq5cU8z6jW7O+YfKGfRmEAhKMimJ3WYWA+fgI7tCLykRyrkmKbIxK+gGTjFkh0bfpb8xcNoiPgRZmE4ijdERIYYcLiQzsh1ICh7OwZGL1dcMLNrynDylM/7+wm7fOVCYK2X/lESsKv6ka1j2NNLaJOcJCwdX92cN+H1XC/aH/oBaNSsUbJHXzufQQgsJVDIoI0+S1OpjOB239o87Ggy+3v+BmUFFCWbBAzIDYmWhAe08IRQs9ShU8Zcwt8xmooAQrnVaVQ26apAXwLQQgPhV6m2bUHi/SHn5pkasH/aHNSBFjzslQLOvnegMD2v6Kyv/es9qb5dojM//TBGjovDpMgT1i7I/4I1CO3Jan86rPwIJVGQg0btnHW/1WTliZJJ4XsEGBPbD+FdLLfkRHNr5CHMUQxdiGW9B0n7WuasUPaDdLPxjDWaSYorpSpSaJVne2AwqvtzW9/gHBAk455ekHgH/5S3xGVwG8V41Aiv9cqe6jImp3FtUoyRAEa17A19GeNwkWcoznOO3q9pSE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
