travis:
  secure:
    BINSTAR_TOKEN: duSaI7KOr5hfFveSrKIe16ZgfoiiF7LtS8REmpXBiFkaISSqT+lYA1yJtGEWmM0YutzZ0bCU+xERcN3LlYC3WNekFYcG2xKCjwKVzcPw0GGwn36QDXRGZ5bOg4fha0aNNVVbL9Y/31t/sr/tth9B9tAc+d8PBaAHFULHOE+DjQFa0zs54DRVCigd/B4HcfKWt5qBF1MgwXvM5cA024KUYGcua/+eZJV/7+I1QYse+J5OMsPelzhgj46dzIxvKXcRbPRhFDQUK/cymu7v8cw9MzRVHN3+AA9OXeJlnJbdRfRfHU7avT5BlsGZtjZlNAGDX9WOoc5wfAQBZGnm5azXMsw7RlXDEyimslaziouDUkYK6u8s3pX33js6o+jTf0jodqR1XaSDzFde0GvTKexWtH/l0QcktoYcsv4t4EgE+5fbtV5nlewPiHWdnzcZ/Ls9LZFisdVlZc3iivtiOwh0uMcEYN/n9nkrGno8OP70ZeJZbBoGwnS2LDBvosRfevJukCEoTPL4K9xSz0SrEg0ccTRyHSsLjCmsGrgbvJT0xp2JBjvYOnCdqCd5/ZeFm7XKObBCo55J7RdjpUsyt1mSdLyLtc/KQ/HfBOug6ShUW0fRoZG//v9GLakp6HzpPHbKQK7c/qfJtVv9V3tFKsVeKTUS3DGevQRNRPtVqjeTIUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
